# Generated by Django 6.0.7 on 2026-07-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=150, unique=True, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія товару',
                'verbose_name_plural': 'Категорії товарів',
                'db_table': 'product_categories',
                'ordering': ['name_category'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False, verbose_name='Артикул (1С)')),
                ('name_product', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('description', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(blank=True, default=15, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'products',
                'ordering': ['name_product'],
            },
        ),
        migrations.CreateModel(
            name='ProductLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вага одиниці (кг)')),
                ('unit_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Довжина одиниці (см)')),
                ('unit_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ширина одиниці (см)')),
                ('unit_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Висота одиниці (см)')),
                ('units_per_box', models.SmallIntegerField(blank=True, null=True, verbose_name='Одиниць у ящику')),
                ('box_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вага ящика (кг)')),
                ('box_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Довжина ящика (см)')),
                ('box_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ширина ящика (см)')),
                ('box_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Висота ящика (см)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Логістика товару',
                'verbose_name_plural': 'Логістика товарів',
                'db_table': 'product_logistics',
            },
        ),
    ]
