# Generated by Django 6.0.7 on 2026-07-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID клієнта (1С)')),
                ('name_customer', models.CharField(max_length=255, verbose_name='Назва клієнта')),
                ('network_customer', models.CharField(blank=True, default='', max_length=150, verbose_name='Напрямок діяльності')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'customers',
                'ordering': ['name_customer'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id_store', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID магазину (1С)')),
                ('name_store', models.CharField(max_length=255, verbose_name='Назва магазину')),
                ('store_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адреса магазину')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stores', to='customers.customer', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазини',
                'db_table': 'stores',
                'ordering': ['name_store'],
            },
        ),
        migrations.CreateModel(
            name='StoreDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=500, verbose_name='Адреса доставки')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основна адреса')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='customers.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Адреса доставки',
                'verbose_name_plural': 'Адреси доставки',
                'db_table': 'store_delivery_addresses',
            },
        ),
    ]
