# Generated by Django 6.0.7 on 2026-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram ID"
            ),
        ),
    ]
