# Generated by Django 6.0.7 on 2026-07-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity', models.CharField(choices=[('ESP', 'ESP'), ('OPT', 'OPT'), ('Rubin', 'Rubin')], max_length=10, verbose_name='Юридична особа')),
                ('waybill_number', models.CharField(max_length=50, verbose_name='Номер накладної')),
                ('waybill_date', models.DateField(verbose_name='Дата накладної')),
                ('line_position', models.SmallIntegerField(verbose_name='Позиція в накладній')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Клієнт (копія)')),
                ('product_name', models.CharField(max_length=255, verbose_name='Товар (копія)')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість')),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна (грн)')),
                ('total_uah', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сума (грн)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Коментар')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Загальна вага (кг)')),
                ('total_volume_cbm', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name="Об'єм (м³)")),
                ('volumetric_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name="Об'ємна вага (кг)")),
                ('delivery_channel', models.CharField(blank=True, choices=[('own', 'Власне авто'), ('hired', 'Найманий транспорт'), ('carrier', 'Служба доставки')], max_length=10, null=True, verbose_name='Канал доставки')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch_id', models.CharField(blank=True, default='', max_length=50, verbose_name='ID імпорту')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_records', to='customers.customer', verbose_name='Клієнт')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_records', to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_records', to='customers.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Рядок накладної',
                'verbose_name_plural': 'Реєстр накладних',
                'db_table': 'waybill_records',
                'ordering': ['-waybill_date', 'waybill_number'],
                'indexes': [models.Index(fields=['waybill_date'], name='waybill_rec_waybill_f2b9bd_idx'), models.Index(fields=['waybill_number'], name='waybill_rec_waybill_daeeac_idx'), models.Index(fields=['delivery_channel'], name='waybill_rec_deliver_a5852d_idx')],
                'unique_together': {('waybill_number', 'line_position')},
            },
        ),
    ]
