# Generated by Django 6.0.7 on 2026-07-09 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=100, verbose_name='Назва авто')),
                ('number_car', models.CharField(max_length=20, unique=True, verbose_name='Держ. номер')),
                ('fuel_card_number', models.BigIntegerField(blank=True, null=True, verbose_name='Номер паливної карти')),
                ('amount_car', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Амортизація (грн/міс)')),
                ('default_tracking_mode', models.CharField(choices=[('daily', 'Щоденний (одометр)'), ('full', 'Повний (кожна точка)')], default='daily', max_length=10, verbose_name='Режим трекінгу (дефолт)')),
                ('status_car', models.CharField(choices=[('active', 'Активне'), ('repair', 'Ремонт'), ('inactive', 'Неактивне')], default='active', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Автопарк',
                'db_table': 'cars',
                'ordering': ['number_car'],
            },
        ),
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(blank=True, default='', max_length=17, verbose_name='VIN код')),
                ('year_manufactured', models.SmallIntegerField(blank=True, null=True, verbose_name='Рік випуску')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Маса авто (кг)')),
                ('payload_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вантажопідйомність (кг)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Довжина (см)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ширина (см)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Висота (см)')),
                ('has_tail_lift', models.BooleanField(default=False, verbose_name='Гідроборт')),
                ('has_trailer', models.BooleanField(default=False, verbose_name='Причіп')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='cars.car', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Характеристики авто',
                'verbose_name_plural': 'Характеристики авто',
                'db_table': 'car_specs',
            },
        ),
        migrations.CreateModel(
            name='CarStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активне'), ('repair', 'Ремонт'), ('inactive', 'Неактивне')], max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Причина / коментар')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cars.car', verbose_name='Авто')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Змінив')),
            ],
            options={
                'verbose_name': 'Журнал статусів авто',
                'verbose_name_plural': 'Журнал статусів авто',
                'db_table': 'car_status_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=150, verbose_name='ПІБ водія')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('drivers_license', models.CharField(blank=True, default='', max_length=50, verbose_name='Посвідчення водія')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='cars.car', verbose_name='Закріплене авто')),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
                'db_table': 'drivers',
                'ordering': ['name_driver'],
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trailer', models.CharField(blank=True, default='', max_length=150, verbose_name='Назва причепа')),
                ('vin_code', models.CharField(blank=True, default='', max_length=17, verbose_name='VIN код')),
                ('model', models.CharField(max_length=100, verbose_name='Модель причепа')),
                ('number_trailer', models.CharField(max_length=20, unique=True, verbose_name='Номерний знак')),
                ('year_manufactured', models.SmallIntegerField(blank=True, null=True, verbose_name='Рік випуску')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trailer', to='cars.car', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Причіп',
                'verbose_name_plural': 'Причепи',
                'db_table': 'trailers',
            },
        ),
        migrations.CreateModel(
            name='MonthlyCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Місяць')),
                ('salary_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ЗП водія (грн)')),
                ('taxes_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Податки із ЗП (грн)')),
                ('depreciation_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Амортизація (грн)')),
                ('repair_actual_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ремонт фактичний (грн)')),
                ('repair_rate_uah_km', models.DecimalField(decimal_places=2, default=2.0, max_digits=6, verbose_name='Ставка ремонту (грн/км)')),
                ('other_costs_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Інші витрати (грн)')),
                ('other_costs_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='monthly_costs', to='cars.car', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Місячні витрати',
                'verbose_name_plural': 'Місячні витрати',
                'db_table': 'monthly_costs',
                'ordering': ['-month'],
                'unique_together': {('car', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RouteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_mode', models.CharField(choices=[('daily', 'Щоденний'), ('full', 'Повний')], max_length=10, verbose_name='Режим трекінгу')),
                ('event_type', models.CharField(choices=[('depot_start', 'Старт зі складу'), ('delivery', 'Вивантаження'), ('parking_end', 'Кінець маршруту'), ('depot_return', 'Повернення на склад'), ('refuel', 'Заправка'), ('other_cost', 'Інші витрати'), ('return_goods', 'Повернення товару'), ('extra_cargo', 'Додатковий вантаж')], max_length=20, verbose_name='Тип події')),
                ('event_ts', models.DateTimeField(verbose_name='Час події')),
                ('odometer_km', models.IntegerField(blank=True, null=True, verbose_name='Одометр (км)')),
                ('pallets_count', models.SmallIntegerField(blank=True, null=True, verbose_name='Кількість палет')),
                ('waybill_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Номер накладної')),
                ('waybill_date', models.DateField(blank=True, null=True, verbose_name='Дата накладної')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Клієнт')),
                ('rejection_full', models.BooleanField(blank=True, null=True, verbose_name='Повна відмова')),
                ('rejection_product_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Артикул (відмова)')),
                ('rejection_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Кількість (відмова)')),
                ('rejection_comment', models.TextField(blank=True, default='')),
                ('fuel_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Паливо (л)')),
                ('fuel_cost_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Паливо (грн)')),
                ('ad_blue_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='AdBlue (л)')),
                ('ad_blue_cost_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AdBlue (грн)')),
                ('other_costs_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Інші витрати (грн)')),
                ('other_costs_comment', models.TextField(blank=True, default='')),
                ('return_client_waybill', models.CharField(blank=True, default='', max_length=50, verbose_name='Накладна клієнта (повернення)')),
                ('extra_from', models.CharField(blank=True, default='', max_length=255)),
                ('extra_to', models.CharField(blank=True, default='', max_length=255)),
                ('extra_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('extra_waybill', models.CharField(blank=True, default='', max_length=50)),
                ('extra_comment', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='route_events', to='cars.car', verbose_name='Авто')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='route_events', to='cars.driver', verbose_name='Водій')),
            ],
            options={
                'verbose_name': 'Подія маршруту',
                'verbose_name_plural': 'Події маршруту',
                'db_table': 'route_events',
                'ordering': ['event_ts'],
                'indexes': [models.Index(fields=['car', 'event_ts'], name='route_event_car_id_993363_idx'), models.Index(fields=['event_type'], name='route_event_event_t_535959_idx')],
            },
        ),
    ]
