# Generated by Django 6.0.7 on 2026-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number_car',
            field=models.CharField(max_length=17, unique=True, verbose_name='Держ. номер'),
        ),
    ]
