# Generated by Django 6.0.7 on 2026-08-04 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0002_alter_car_number_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="telegram_id",
        ),
    ]
