# Generated by Django 6.0.7 on 2026-08-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('mist_express', 'Міст Експрес'), ('other', 'Інша служба')], help_text='Служба доставки, яка прийняла відправлення', max_length=20, verbose_name='Служба доставки')),
                ('ttn', models.CharField(help_text='Номер ТТН, який прийняла відправлення служба доставки', max_length=50, unique=True, verbose_name='Номер ТТН')),
                ('shipment_date', models.DateField(help_text='Дата, на яку було передано відправлення службі доставки', verbose_name='Дата передачі відправлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата створення запису', verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Відправлення служби доставки',
                'verbose_name_plural': 'Відправлення службам доставки',
                'db_table': 'carrier_shipments',
                'ordering': ['-shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='HiredTransportTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(help_text='Номер авто, який використовувався на рейсі', max_length=20, verbose_name='Номер авто (найманий)')),
                ('route_name', models.CharField(help_text='Назва маршруту, який був використаний на рейсі', max_length=255, verbose_name='Назва маршруту')),
                ('trip_date', models.DateField(help_text='Дата, на яку був виконаний рейс', verbose_name='Дата рейсу')),
                ('cost_uah', models.DecimalField(decimal_places=2, help_text='Вартість доставки, вказана в гривнях', max_digits=10, verbose_name='Вартість доставки (грн)')),
                ('pallets_count', models.SmallIntegerField(blank=True, help_text='Кількість палет, які були використані на рейсі', null=True, verbose_name='Кількість палет')),
                ('comment', models.TextField(blank=True, default='', help_text='Додатковий коментар до рейсу', verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата створення запису', verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Рейс найманого транспорту',
                'verbose_name_plural': 'Рейси найманим транспортом',
                'db_table': 'hired_transport_trips',
                'ordering': ['-trip_date'],
            },
        ),
        migrations.CreateModel(
            name='CarrierShipmentWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(help_text='Номер відправлення', max_length=50, unique=True, verbose_name='Номер відправлення')),
                ('shipment', models.ForeignKey(help_text='Відправлення, до якого належить відправлення', on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='logistics.carriershipment', verbose_name='Відправлення')),
            ],
            options={
                'verbose_name': 'Накладна відправлення',
                'verbose_name_plural': 'Накладні відправлення',
                'db_table': 'carrier_shipment_waybills',
            },
        ),
        migrations.CreateModel(
            name='HiredTripWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(help_text='Номер накладної, який приєднано до рейсу', max_length=20, unique=True, verbose_name='Номер накладної')),
                ('trip', models.ForeignKey(help_text='Рейс, до якого прикріплено відправлення', on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='logistics.hiredtransporttrip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Накладна найманого транспорту',
                'verbose_name_plural': 'Накладні найманим транспортом',
                'db_table': 'hired_trip_waybills',
            },
        ),
        migrations.CreateModel(
            name='CarrierCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttn', models.CharField(help_text='Номер ТТН', max_length=50, verbose_name='Номер ТТН')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Вага відправлення в кілограмах', max_digits=10, verbose_name='Вага в кілограмах')),
                ('cost_uah', models.DecimalField(decimal_places=2, help_text='Вартість відправлення в гривнях', max_digits=10, verbose_name='Вартість в гривнях')),
                ('cost_date', models.DateField(help_text='Дата відправлення', verbose_name='Дата відправлення')),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='Дата і час імпорту', verbose_name='Дата і час імпорту')),
                ('shipment', models.ForeignKey(blank=True, help_text='Відправлення, до якого належить відправлення', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='logistics.carriershipment', verbose_name='Відправлення')),
            ],
            options={
                'verbose_name': 'Витрата служби доставки',
                'verbose_name_plural': 'Витрати служб доставки',
                'db_table': 'carrier_costs',
                'ordering': ['-cost_date'],
                'indexes': [models.Index(fields=['ttn'], name='carrier_cos_ttn_e914e2_idx')],
            },
        ),
    ]
