# Generated by Django 6.0.7 on 2026-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredtripwaybill',
            name='waybill_number',
            field=models.CharField(help_text='Номер накладної, який приєднано до рейсу', max_length=50, unique=True, verbose_name='Номер накладної'),
        ),
    ]
