# Generated by Django 6.0.7 on 2026-10-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0002_alter_hiredtripwaybill_waybill_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carriershipmentwaybill",
            name="waybill_number",
            field=models.CharField(
                db_index=True,
                help_text="Номер відправлення",
                max_length=50,
                verbose_name="Номер відправлення",
            ),
        ),
        migrations.AddConstraint(
            model_name="carriershipmentwaybill",
            constraint=models.UniqueConstraint(
                fields=("shipment", "waybill_number"),
                name="uniq_carrier_shipment_waybill",
            ),
        ),
    ]
